repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.4.5
    hooks:
      # - id: sqlfluff-lint
      #   args: [--config, 'sqlfluff.cfg']
      - id: sqlfluff-fix
        args: [--config, 'sqlfluff.cfg', --rules, 'ffLT02,LT12,CP01,ST06,LT09,LT01']
        